// Mapping of process executable names (lowercase, with .exe) to display name.
// Match is exact on the lowercased process name from `tasklist`.
export const GAME_CATALOG = {
    'enshrouded.exe': 'Enshrouded',
    'bf6.exe': 'Battlefield 6',
    'leagueclient.exe': 'League of Legends',
    'valorant-win64-shipping.exe': 'Valorant',
    'cs2.exe': 'Counter-Strike 2',
    'csgo.exe': 'Counter-Strike: Global Offensive',
    'fortniteclient-win64-shipping.exe': 'Fortnite',
    'rocketleague.exe': 'Rocket League',
    'gta5.exe': 'Grand Theft Auto V',
    'gtav.exe': 'Grand Theft Auto V',
    'rdr2.exe': 'Red Dead Redemption 2',
    'tslgame.exe': 'PUBG: Battlegrounds',
    'minecraft.exe': 'Minecraft',
    'minecraftlauncher.exe': 'Minecraft',
    'overwatch.exe': 'Overwatch 2',
    'wow.exe': 'World of Warcraft',
    'destiny2.exe': 'Destiny 2',
    'r5apex.exe': 'Apex Legends',
    'r5apex_dx12.exe': 'Apex Legends',
    'escapefromtarkov.exe': 'Escape from Tarkov',
    'starcitizen.exe': 'Star Citizen',
    'eldenring.exe': 'Elden Ring',
    'witcher3.exe': 'The Witcher 3',
    'cyberpunk2077.exe': 'Cyberpunk 2077',
    'helldivers2.exe': 'Helldivers 2',
    'hd2.exe': 'Helldivers 2',
    'rustclient.exe': 'Rust',
    'factorygame-win64-shipping.exe': 'Satisfactory',
    'palworld-win64-shipping.exe': 'Palworld',
    'bg3.exe': "Baldur's Gate 3",
    'bg3_dx11.exe': "Baldur's Gate 3",
    'ck3.exe': 'Crusader Kings III',
    'stellaris.exe': 'Stellaris',
    'factorio.exe': 'Factorio',
    'terraria.exe': 'Terraria',
    'hades2.exe': 'Hades II',
    'hades.exe': 'Hades',
    'noita.exe': 'Noita',
    'riskofrain2.exe': 'Risk of Rain 2',
    'deadcells.exe': 'Dead Cells',
    'eldenringeasyantictheft.exe': 'Elden Ring',
    'marvel-win64-shipping.exe': 'Marvel Rivals',
    'pathofexile.exe': 'Path of Exile',
    'pathofexile_x64.exe': 'Path of Exile',
    'pathofexilesteam.exe': 'Path of Exile',
};
